[build]
  command = "npm run build"
  publish = "."

# Pretty URLs: /slug → /slug.html
[[redirects]]
  from = "/:page"
  to = "/:page.html"
  status = 200

# Home
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200